#server config
server:
  port: 8091
  #设定项目发布路径
  servlet:
    # /代表缺省值目录
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///jinggo_db?serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

      #Redis 配置
  redis:
    #redis数据库索引
    database: 0
    #redis服务器地址
    host: 192.168.153.11
    #redis服务器连接端口
    port: 6379
    #redis服务器连接密码，默认为空
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 8
        #连接池最小空闲连接
        min-idle: 0

